### ISSUE TITLE
[broken-step] install-dotnetcore - GitHub repo does not exist

### ISSUE THREAD

**Issue by delixfe** [bitrise-io/bitrise-steplib#2725]
The step at https://github.com/bitrise-io/bitrise-steplib/tree/d3581bdf1de00ddbbe0f0c7113f75d855312e8b1/steps/install-dotnetcore/1.0.0 links to a repo that does not exist.

**Comment by non-binary** [comment]
Hi @delixfe,

Unfortunately this means that the user deleted the repository which deleted the source code for the step which means it will no longer be usable. I would recommend reaching out to the developer to see if they can re-add the code otherwise please follow-up and we will remove the step from the library.

**Comment by delixfe** [comment]
Hi @stefandevo,

you published the bitrise step install-dotnetcore pointing to https://github.com/stefandevo/bitrise-dotnetcore-step. This repo does not seem to exist any more. Do you want to re-add it or should they remove the step definition.

**Comment by sylank** [comment]
Hi,

We have deprecated this step because of a lack of maintenance 😥 .

@delixfe if you missing this step then go ahead, feel free to implement this step again. We are welcome the open-source contributions 😺 .

Some info:
https://devcenter.bitrise.io/contributors/create-your-own-step/
https://github.com/bitrise-steplib/steps-install-react-native
